type CatalogLogo = {
  id: string;
  domain: string;
  answer: string;
  aliases: string[];
  category: string;
  difficulty: "easy" | "medium" | "hard";
  imageUrl: string;
};

type BrandSeed = readonly [domain: string, answer: string, aliases?: readonly string[]];

export const logoDomainCorrections: Readonly<Record<string, string>> = {
  "burgerking.com": "burgerking.fr",
};

export const correctedLogoDomain = (domain: string) => logoDomainCorrections[domain] ?? domain;

const brandSeeds: BrandSeed[] = [
  ["abercrombie.com", "Abercrombie & Fitch", ["abercrombie"]],
  ["accenture.com", "Accenture"],
  ["acer.com", "Acer"],
  ["activision.com", "Activision"],
  ["adobe.com", "Adobe"],
  ["airfrance.com", "Air France"],
  ["alibaba.com", "Alibaba"],
  ["aliexpress.com", "AliExpress", ["ali express"]],
  ["allianz.com", "Allianz"],
  ["alpinecars.com", "Alpine"],
  ["amd.com", "AMD"],
  ["americanexpress.com", "American Express", ["amex"]],
  ["amg.com", "AMG", ["mercedes amg"]],
  ["android.com", "Android"],
  ["armani.com", "Armani", ["giorgio armani"]],
  ["asos.com", "ASOS"],
  ["astonmartin.com", "Aston Martin"],
  ["asus.com", "Asus"],
  ["atlassian.com", "Atlassian"],
  ["axa.com", "AXA"],
  ["bacardi.com", "Bacardi"],
  ["balenciaga.com", "Balenciaga"],
  ["barclays.com", "Barclays"],
  ["barilla.com", "Barilla"],
  ["baskinrobbins.com", "Baskin-Robbins", ["baskin robbins"]],
  ["bayer.com", "Bayer"],
  ["bbc.com", "BBC"],
  ["beatsbydre.com", "Beats", ["beats by dre"]],
  ["benetton.com", "Benetton"],
  ["bentley.com", "Bentley"],
  ["bershka.com", "Bershka"],
  ["bic.com", "BIC"],
  ["billa.com", "Billa"],
  ["binance.com", "Binance"],
  ["blackberry.com", "BlackBerry", ["black berry"]],
  ["blizzard.com", "Blizzard", ["blizzard entertainment"]],
  ["bnp-paribas.com", "BNP Paribas", ["bnp"]],
  ["booking.com", "Booking.com", ["booking"]],
  ["bosch.com", "Bosch"],
  ["bose.com", "Bose"],
  ["bp.com", "BP"],
  ["bridgestone.com", "Bridgestone"],
  ["bugatti.com", "Bugatti"],
  ["bulgari.com", "Bulgari", ["bvlgari"]],
  ["burberry.com", "Burberry"],
  ["byd.com", "BYD"],
  ["cadbury.co.uk", "Cadbury"],
  ["calvinklein.com", "Calvin Klein", ["ck"]],
  ["canalplus.com", "Canal+", ["canal plus"]],
  ["canon.com", "Canon"],
  ["carrefour.com", "Carrefour"],
  ["cartier.com", "Cartier"],
  ["casio.com", "Casio"],
  ["caterpillar.com", "Caterpillar", ["cat"]],
  ["celine.com", "Celine", ["céline"]],
  ["chevrolet.com", "Chevrolet", ["chevy"]],
  ["chipotle.com", "Chipotle"],
  ["chupa-chups.com", "Chupa Chups"],
  ["cisco.com", "Cisco"],
  ["citroen.com", "Citroën", ["citroen"]],
  ["cnn.com", "CNN"],
  ["colgate.com", "Colgate"],
  ["converse.com", "Converse"],
  ["costco.com", "Costco"],
  ["credit-agricole.com", "Crédit Agricole", ["credit agricole"]],
  ["crocs.com", "Crocs"],
  ["dacia.com", "Dacia"],
  ["danone.com", "Danone"],
  ["dell.com", "Dell"],
  ["delta.com", "Delta Air Lines", ["delta"]],
  ["desigual.com", "Desigual"],
  ["dhl.com", "DHL"],
  ["diageo.com", "Diageo"],
  ["diesel.com", "Diesel"],
  ["dior.com", "Dior", ["christian dior"]],
  ["discovery.com", "Discovery"],
  ["dominos.com", "Domino's", ["dominos", "domino's pizza"]],
  ["doordash.com", "DoorDash", ["door dash"]],
  ["doritos.com", "Doritos"],
  ["drpepper.com", "Dr Pepper"],
  ["dropbox.com", "Dropbox"],
  ["ducati.com", "Ducati"],
  ["dunkin.com", "Dunkin'", ["dunkin donuts"]],
  ["easyjet.com", "easyJet", ["easy jet"]],
  ["ebay.com", "eBay"],
  ["electrolux.com", "Electrolux"],
  ["emirates.com", "Emirates"],
  ["epson.com", "Epson"],
  ["etsy.com", "Etsy"],
  ["evernote.com", "Evernote"],
  ["expedia.com", "Expedia"],
  ["facebook.com", "Facebook", ["fb"]],
  ["fedex.com", "FedEx", ["fed ex"]],
  ["fila.com", "Fila"],
  ["fnac.com", "Fnac"],
  ["fossil.com", "Fossil"],
  ["foursquare.com", "Foursquare"],
  ["fox.com", "Fox"],
  ["fujifilm.com", "Fujifilm", ["fuji film"]],
  ["g-star.com", "G-Star RAW", ["g star", "gstar"]],
  ["gap.com", "Gap"],
  ["garmin.com", "Garmin"],
  ["garnier.com", "Garnier"],
  ["gillette.com", "Gillette"],
  ["github.com", "GitHub", ["git hub"]],
  ["givenchy.com", "Givenchy"],
  ["godaddy.com", "GoDaddy", ["go daddy"]],
  ["gopro.com", "GoPro", ["go pro"]],
  ["guinness.com", "Guinness"],
  ["h-m.com", "H&M", ["hm"]],
  ["haribo.com", "Haribo"],
  ["harleydavidson.com", "Harley-Davidson", ["harley davidson", "harley"]],
  ["heineken.com", "Heineken"],
  ["hellokitty.com", "Hello Kitty"],
  ["hermes.com", "Hermès", ["hermes"]],
  ["hilton.com", "Hilton"],
  ["hisense.com", "Hisense"],
  ["hitachi.com", "Hitachi"],
  ["hm.com", "H&M", ["hm"]],
  ["hp.com", "HP", ["hewlett packard"]],
  ["hsbc.com", "HSBC"],
  ["huawei.com", "Huawei"],
  ["hugoboss.com", "Hugo Boss", ["boss"]],
  ["hyundai.com", "Hyundai"],
  ["ibm.com", "IBM"],
  ["infiniti.com", "Infiniti"],
  ["ing.com", "ING"],
  ["jaguar.com", "Jaguar"],
  ["jbl.com", "JBL"],
  ["jeep.com", "Jeep"],
  ["johnsonandjohnson.com", "Johnson & Johnson", ["j&j"]],
  ["jordan.com", "Jordan", ["air jordan"]],
  ["kappa.com", "Kappa"],
  ["kelloggs.com", "Kellogg's", ["kelloggs"]],
  ["kenzo.com", "Kenzo"],
  ["kia.com", "Kia"],
  ["kitkat.com", "KitKat", ["kit kat"]],
  ["kodak.com", "Kodak"],
  ["konami.com", "Konami"],
  ["krispykreme.com", "Krispy Kreme"],
  ["lamborghini.com", "Lamborghini", ["lambo"]],
  ["landrover.com", "Land Rover"],
  ["lays.com", "Lay's", ["lays"]],
  ["lecoqsportif.com", "Le Coq Sportif"],
  ["lenovo.com", "Lenovo"],
  ["levis.com", "Levi's", ["levis"]],
  ["lg.com", "LG"],
  ["linkedin.com", "LinkedIn", ["linked in"]],
  ["logitech.com", "Logitech"],
  ["loreal.com", "L'Oréal", ["loreal", "l'oréal"]],
  ["lotto.com", "Lotto"],
  ["lotus.com", "Lotus"],
  ["maersk.com", "Maersk"],
  ["mango.com", "Mango"],
  ["marriott.com", "Marriott"],
  ["maserati.com", "Maserati"],
  ["maybelline.com", "Maybelline"],
  ["mazda.com", "Mazda"],
  ["mcdelivery.com", "McDelivery", ["mc delivery"]],
  ["michelin.com", "Michelin"],
  ["milka.com", "Milka"],
  ["mini.com", "Mini"],
  ["mitsubishi-motors.com", "Mitsubishi"],
  ["moncler.com", "Moncler"],
  ["monsterenergy.com", "Monster Energy", ["monster"]],
  ["motorola.com", "Motorola"],
  ["msi.com", "MSI"],
  ["mugler.com", "Mugler"],
  ["nescafe.com", "Nescafé", ["nescafe"]],
  ["nespresso.com", "Nespresso"],
  ["nestle.com", "Nestlé", ["nestle"]],
  ["newbalance.com", "New Balance", ["newbalance"]],
  ["nissan.com", "Nissan"],
  ["nokia.com", "Nokia"],
  ["nvidia.com", "Nvidia"],
  ["oakley.com", "Oakley"],
  ["olympus.com", "Olympus"],
  ["oneplus.com", "OnePlus", ["one plus"]],
  ["opel.com", "Opel"],
  ["oracle.com", "Oracle"],
  ["oreo.com", "Oreo"],
  ["panasonic.com", "Panasonic"],
  ["pandora.net", "Pandora"],
  ["patagonia.com", "Patagonia"],
  ["peugeot.com", "Peugeot"],
  ["philips.com", "Philips"],
  ["pinterest.com", "Pinterest"],
  ["pixar.com", "Pixar"],
  ["pizza-hut.com", "Pizza Hut", ["pizzahut"]],
  ["playmobil.com", "Playmobil"],
  ["polaroid.com", "Polaroid"],
  ["prada.com", "Prada"],
  ["pringles.com", "Pringles"],
  ["pullandbear.com", "Pull&Bear", ["pull and bear"]],
  ["quiksilver.com", "Quiksilver"],
  ["ray-ban.com", "Ray-Ban", ["rayban"]],
  ["reebok.com", "Reebok"],
  ["revolut.com", "Revolut"],
  ["riotgames.com", "Riot Games", ["riot"]],
  ["rolls-roycemotorcars.com", "Rolls-Royce", ["rolls royce"]],
  ["ryanair.com", "Ryanair"],
  ["saab.com", "Saab"],
  ["salesforce.com", "Salesforce"],
  ["sanpellegrino.com", "S.Pellegrino", ["san pellegrino"]],
  ["sap.com", "SAP"],
  ["sega.com", "Sega"],
  ["sephora.com", "Sephora"],
  ["skoda-auto.com", "Škoda", ["skoda"]],
  ["skype.com", "Skype"],
  ["slack.com", "Slack"],
  ["snapchat.com", "Snapchat", ["snap"]],
  ["sony.com", "Sony"],
  ["soundcloud.com", "SoundCloud", ["sound cloud"]],
  ["spacex.com", "SpaceX", ["space x"]],
  ["speedo.com", "Speedo"],
  ["sprite.com", "Sprite"],
  ["subway.com", "Subway"],
  ["suzuki.com", "Suzuki"],
  ["swatch.com", "Swatch"],
  ["tacobell.com", "Taco Bell"],
  ["telegram.org", "Telegram"],
  ["tesco.com", "Tesco"],
  ["thebodyshop.com", "The Body Shop", ["body shop"]],
  ["thenorthface.com", "The North Face"],
  ["tiffany.com", "Tiffany & Co.", ["tiffany"]],
  ["tinder.com", "Tinder"],
  ["tommy.com", "Tommy Hilfiger", ["tommy"]],
  ["totalenergies.com", "TotalEnergies", ["total energies", "total"]],
  ["tous.com", "Tous"],
  ["tripadvisor.com", "Tripadvisor", ["trip advisor"]],
  ["twitch.tv", "Twitch"],
  ["underarmour.com", "Under Armour"],
  ["uniqlo.com", "Uniqlo"],
  ["ups.com", "UPS"],
  ["vans.com", "Vans"],
  ["versace.com", "Versace"],
  ["viber.com", "Viber"],
  ["vimeo.com", "Vimeo"],
  ["volvo.com", "Volvo"],
  ["warnerbros.com", "Warner Bros.", ["warner bros", "warner brothers"]],
  ["whatsapp.com", "WhatsApp", ["whats app"]],
  ["wikipedia.org", "Wikipedia"],
  ["windows.com", "Windows", ["microsoft windows"]],
  ["wordpress.com", "WordPress", ["word press"]],
  ["xiaomi.com", "Xiaomi"],
  ["yahoo.com", "Yahoo!"],
  ["yves-rocher.com", "Yves Rocher"],
  ["zalando.com", "Zalando"],
  ["zara.com", "Zara"],
  ["zoom.us", "Zoom"],
  ["adp.com", "ADP"],
  ["aig.com", "AIG"],
  ["alfa-romeo.com", "Alfa Romeo"],
  ["alstom.com", "Alstom"],
  ["amazonprime.com", "Amazon Prime", ["prime video"]],
  ["amtrak.com", "Amtrak"],
  ["baileys.com", "Baileys"],
  ["bankofamerica.com", "Bank of America"],
  ["betclic.com", "Betclic"],
  ["bimba-y-lola.com", "Bimba y Lola"],
  ["bostondynamics.com", "Boston Dynamics"],
  ["breguet.com", "Breguet"],
  ["breitling.com", "Breitling"],
  ["bristolmyerssquibb.com", "Bristol Myers Squibb", ["bms"]],
  ["capgemini.com", "Capgemini"],
  ["championsleague.com", "Champions League", ["uefa champions league"]],
  ["chopard.com", "Chopard"],
  ["citibank.com", "Citibank", ["citi"]],
  ["clinique.com", "Clinique"],
  ["cloudflare.com", "Cloudflare"],
  ["coinbase.com", "Coinbase"],
  ["corona.com", "Corona"],
  ["coursera.org", "Coursera"],
  ["deezer.com", "Deezer"],
  ["deliveroo.com", "Deliveroo"],
  ["discord.com", "Discord"],
  ["dolcegabbana.com", "Dolce & Gabbana", ["dolce and gabbana", "d&g"]],
  ["dreamworks.com", "DreamWorks", ["dream works"]],
  ["ea.com", "Electronic Arts", ["ea", "ea games"]],
  ["esso.com", "Esso"],
  ["fanta.com", "Fanta"],
  ["farfetch.com", "Farfetch"],
  ["fiat.com", "Fiat"],
  ["firefox.com", "Firefox", ["mozilla firefox"]],
  ["fitbit.com", "Fitbit"],
  ["flickr.com", "Flickr"],
  ["footlocker.com", "Foot Locker"],
  ["generalelectric.com", "General Electric", ["ge"]],
  ["glovoapp.com", "Glovo"],
  ["hbo.com", "HBO"],
  ["hellmanns.com", "Hellmann's", ["hellmanns"]],
  ["indeed.com", "Indeed"],
  ["jackdaniels.com", "Jack Daniel's", ["jack daniels"]],
  ["jagermeister.com", "Jägermeister", ["jagermeister"]],
  ["jysk.com", "JYSK"],
  ["klarna.com", "Klarna"],
  ["lastminute.com", "lastminute.com", ["last minute"]],
  ["lipton.com", "Lipton"],
  ["marlboro.com", "Marlboro"],
  ["mattel.com", "Mattel"],
  ["mcdonalds.fr", "McDonald's France", ["mcdonalds france", "mcdo"]],
  ["medium.com", "Medium"],
  ["merrell.com", "Merrell"],
  ["moet.com", "Moët & Chandon", ["moet", "moet chandon"]],
  ["monday.com", "monday.com", ["monday"]],
  ["nationalgeographic.com", "National Geographic", ["nat geo"]],
  ["netapp.com", "NetApp", ["net app"]],
  ["notion.so", "Notion"],
  ["novotel.com", "Novotel"],
  ["oldnavy.com", "Old Navy"],
  ["onlyfans.com", "OnlyFans", ["only fans"]],
  ["openai.com", "OpenAI", ["open ai"]],
  ["paramount.com", "Paramount"],
  ["patek.com", "Patek Philippe", ["patek"]],
  ["pirelli.com", "Pirelli"],
  ["pizzahut.com", "Pizza Hut", ["pizza hut"]],
  ["porsche-design.com", "Porsche Design"],
  ["ralphlauren.com", "Ralph Lauren", ["polo ralph lauren"]],
  ["reddit.com", "Reddit"],
  ["replit.com", "Replit"],
  ["rimowa.com", "Rimowa"],
  ["roblox.com", "Roblox"],
  ["rockstargames.com", "Rockstar Games", ["rockstar"]],
  ["samsungmobile.com", "Samsung Mobile"],
  ["schweppes.com", "Schweppes"],
  ["shopify.com", "Shopify"],
  ["siemens.com", "Siemens"],
  ["skyscanner.com", "Skyscanner", ["sky scanner"]],
  ["steam.com", "Steam"],
  ["stellantis.com", "Stellantis"],
  ["stripe.com", "Stripe"],
  ["supercell.com", "Supercell"],
  ["supreme.com", "Supreme"],
  ["t-mobile.com", "T-Mobile", ["tmobile"]],
  ["tagheuer.com", "TAG Heuer", ["tag heuer"]],
  ["temu.com", "Temu"],
  ["threads.net", "Threads"],
  ["timberland.com", "Timberland"],
  ["tissotwatches.com", "Tissot"],
  ["tnt.com", "TNT"],
  ["tumblr.com", "Tumblr"],
  ["twix.com", "Twix"],
  ["uber-eats.com", "Uber Eats", ["ubereats"]],
  ["unilever.com", "Unilever"],
  ["valentino.com", "Valentino"],
  ["veuve-clicquot.com", "Veuve Clicquot"],
  ["vodafone.com", "Vodafone"],
  ["waze.com", "Waze"],
  ["we-transfer.com", "WeTransfer", ["we transfer"]],
  ["westernunion.com", "Western Union"],
  ["wise.com", "Wise"],
  ["x.com", "X", ["twitter"]],
  ["youtubemusic.com", "YouTube Music"],
  ["zendesk.com", "Zendesk"],
];

const idFromDomain = (domain: string) =>
  domain.replace(/^www\./, "").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "");

export const additionalLogos: CatalogLogo[] = brandSeeds.map(
  ([sourceDomain, answer, aliases = []]) => {
    const domain = correctedLogoDomain(sourceDomain);
    return {
      id: idFromDomain(sourceDomain),
      domain,
      answer,
      aliases: [...aliases],
      category: "marques",
      difficulty: "medium",
      imageUrl: `brandfetch://${domain}`,
    };
  },
);
